from . import fbref_scraper
from . import fbref_ls_scraper
from . import fbref_teams_scraper
from . import fbref_tls_scraper
from . import fbref_ptls_scraper
from . import fbref_players_scraper
from . import fbref_matches_scraper
from . import fbref_team_matches_scraper
from . import fbref_player_matches_scraper
from . import api_scraper
